parameters:
  run_workflow_build:
    default: true
    type: boolean

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: medium

    steps:
      - checkout
      - run: bash .circleci/start.sh | ./loop.sh

workflows:
  build:
    when: << pipeline.parameters.run_workflow_build >>
    jobs:
      - build
